name: Generate graph visualization from logic
on:
  workflow_dispatch:
jobs:
  generate-graph-viz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          check-latest: true

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel

      - name: Install pygraphviz
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz graphviz-dev
          pip install pygraphviz

      - name: Install randomizer dependencies
        run: pip install -e .

      - name: Generate graph PNGs
        run: python scripts/graphviz.py

      - name: Upload PNGs
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: graphs
